apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sniffit.fullname" . }}-auth
  labels:
    {{- include "sniffit.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.config.database.url }}
  database-url: {{ .Values.config.database.url | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.sessionSecret }}
  session-secret: {{ .Values.auth.sessionSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.oidc.clientSecret }}
  oidc-client-secret: {{ .Values.auth.oidc.clientSecret | b64enc | quote }}
  {{- end }}
