apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sniffit.fullname" . }}-config
  labels:
    {{- include "sniffit.labels" . | nindent 4 }}
type: Opaque
data:
  openrouter-key: {{ .Values.config.openRouterKey | b64enc | quote }}

