apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sniffit.fullname" . }}-config
  labels:
    {{- include "sniffit.labels" . | nindent 4 }}
type: Opaque
data:
  openrouter-key: {{ .Values.config.openRouterKey | b64enc | quote }}
{{ if .Values.webhook.certManager.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "sniffit.fullname" . }}-webhook-tls
  labels:
    {{- include "sniffit.labels" . | nindent 4 }}
spec:
  secretName: {{ include "sniffit.fullname" . }}-webhook-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    {{- toYaml .Values.webhook.certManager.issuerRef | nindent 4 }}
  commonName: {{ include "sniffit.fullname" . }}.{{ .Release.Namespace }}.svc
  dnsNames:
    - {{ include "sniffit.fullname" . }}.{{ .Release.Namespace }}.svc
    - {{ include "sniffit.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
{{ end }}
